### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by xiangmeng4geo** [cybergrind/safe_logger#1]
Hi
When I use this lib,I meet some error. I think some bug in version 1.2.1.
the error is:
```
   th = TimedRotatingFileHandlerSafe(filename=self.logger_file, when="midnight", backupCount=10)
  File "/opt/WeatherDataCenter/wdc_env/lib/python2.7/site-packages/safe_logger/__init__.py", line 10, in __init__
    super().__init__(filename, when=when, backupCount=backupCount, **kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

I think super may be call like :

super(TimedRotatingFileHandlerSafe,self).__init__(filename, when=when, backupCount=backupCount, **kwargs)

**Comment by cybergrind** [comment]
@xiangmeng4geo oh, it seems you're using python2. Am I right?

**Comment by cybergrind** [comment]
I've released 1.3.1 version with this particular fix. 
It's a shame that it contains no tests but it was so battle-tested for years so I hoped that tests aren't required.

Could you please confirm if 1.3.1 works for you and close ticket if it is ok?

**Comment by xiangmeng4geo** [comment]
Yes,we are using python 2.7.
OK,I will try it next week. Thank you.

**Comment by xiangmeng4geo** [comment]
Sorry about feedback late,when I use 1.3.1, I got error like:

Traceback (most recent call last):
  File "big_screen.py", line 67, in <module>
    big_screen_log = LoggerUtils("big_screen", "big_screen.log").get_logger()
  File "big_screen.py", line 61, in get_logger
    th = TimedRotatingFileHandlerSafe(filename=self.logger_file, when="midnight", backupCount=10)
  File "/usr/lib/python2.6/site-packages/safe_logger/__init__.py", line 10, in __init__
    super(TimedRotatingFileHandlerSafe, self).__init__(filename, when=when, backupCount=backupCount, **kwargs)
TypeError: super() argument 1 must be type, not classobj

And the python version on this server is 2.6.6
